### ISSUE TITLE
UI error:  'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by Anudha** [mompiou/pycotem#4]
**pycotem\diffraction\__main__.py", line 186, in angle_check**

**inc = ui.ListBox_d_2.currentItem().text().split(',')**

**AttributeError: 'NoneType' object has no attribute 'text'**

This error comes up when using the Diffraction GUI.

**Comment by ndattani** [comment]
Just so you know, this question was also asked at [Matter Modeling Stack Exchange](https://mattermodeling.stackexchange.com/q/6269/5) where you could earn a decent amount of currency for answering it.

**Comment by mompiou** [comment]
It seems to me that the error comes from the fact that you forgot to select a measurement in the ```Dist, Incl``` box before adding the data. Please refer to the [documentation](https://mompiou.github.io/pycotem/diffraction/#workflow)

**Comment by ndattani** [comment]
Thanks @mompiou! Would you consider writing that answer at MMSE too, so that we can close the question there? Usually we would not write someone else's answer on their behalf!
