### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by victorbisheng** [mompiou/pycotem#5]
When I am using the kikuchi section, I want to add more Kikuchi tapes to my graph, but when I add a lot of Kikuchi tapes, the software cannot run and it shows an error: too many indices for array: array is 1- dimensional, but 3 were indexed.Can I ask what is the error? Thank you.

**Comment by mompiou** [comment]
This is probably because the program does not find any solution. Please use the test image, in the test folder and the test.txt file for the setting to see if it works properly on your system. Then, check your calibration.  Note that you can use up to 6 bands.

**Comment by victorbisheng** [comment]
I can use this software to index many pattern, but some pictures will have the kind of error I mentioned. How to solve this kind of error?

**Comment by mompiou** [comment]
Could you send me a link to the pattern and indicate me the settings ?

**Comment by victorbisheng** [comment]
https://www.dropbox.com/scl/fi/yj25qs3fsnwij9hd4nz2s/Document.docx?dl=0&rlkey=hrc9nwgs6yto4vvynj074a1w9
this is the link to the pattern

**Comment by mompiou** [comment]
Thank you. It seems to me that the pattern can be indexed, showing a <001> zone axis. Please check as i'm not sure about the correct image size and i did not change the calibration file. I faced the error you mentioned once but was not able to reproduce it. If you do know how to find it, please let me know.

![image](https://user-images.githubusercontent.com/10402089/130329038-5ecf822e-5a18-4951-85ee-f1097fc57018.png)

I faced the error you mentioned once but was not able to reproduce it. If you do know how to find it, please let me know.

**Comment by mompiou** [comment]
I've removed the error in the latest version. It seems to happen when there's no solution found.
